### PR TITLE
new Feature: LowEndTrim

### PR DESCRIPTION
**Pull request by chrismerck**
Screen Shot 2020-04-09 at 10 32 32

DRAFT until we've completed the implementation.

### CODE REVIEW

**Comment by jdlambert** [comment]
We need to make clear when this is an option. Is it SBB only? Is it available but read-only in Bridge devices (most of them that I'm aware of have minimum brightnesses of 20)

**Comment by chrismerck** [comment]
I'll open a PR for a `devices/<dev_id>.features` list which will contain the list of available features, to reduce the guess-and-check that is currently required.

My thought is that the feature is available whenever the feature is available... like, you need to check to see if it is exposing that on the API. Will the Features List help? Or do you mean that the docs should give some expectation of where you can get this feature?

**Comment by jdlambert** [comment]
> Or do you mean that the docs should give some expectation of where you can get this feature?

Yeah, this is what I mean. Really: should this be available on Bridge devices? Since the majority of brightness devices have built-in minimums, it would be fine to make the trim higher, but the trim couldn't go below a certain point.

Or we could just make this read-only for bridges? Or do we just not do anything here for Bridge? With either of those options, it should probably be noted in the docs.

**Comment by chrismerck** [comment]
Ok, I added an availability comment. But I feel that a more sustainable approach would be a compatibility list: Bridge compatibility list showing features available (with any caveats), and SBB products listing their Features (and properties like max_speed). Will need to discuss internally.

**Comment by chrismerck** [comment]
Just saw this:

> I get that "low end trim" is the industry term for this, but would describing the limit in a non-industry way like `min_brightness` potentially be ambiguous or unclear?

Yeah I certainly considered `min_brightness` and had to look up what it was typically called in the industry. But, I'd prefer to use the industry appropriate term whenever possible. Cf. "uplight" rather than "top light" or other possible rendering.

I don't want to call it Minimum Brightness because, if you set something called `min_brightness` to 20%, you'd expect that if brightness=20 and you call DecreaseBrightness(5) that it would not go to 15.

It's really about subtly changing (trimming) how `brightness` is interpreted, rather than limiting the range of `brightness`. I like that "trim" seems to suggest that without having to introduce terms to explicitely name that lower-level below `brightness` (duty cycle or something).

**Comment by jdlambert** [comment]
> I don't want to call it Minimum Brightness because, if you set something called `min_brightness` to 20%, you'd expect that if brightness=20 and you call DecreaseBrightness(5) that it would not go to 15.

Yeah, I thought of this situation after posting. That'd be very confusing! `low_end_trim` it is.

**Pull request merged**
