### PR TITLE
Add a 'not set' status to 'sys/wifi/sta'

### PR DESCRIPTION
**Pull request by marciogranzotto**
As discussed, this changes the behavior of Wi-Fi not being set to return an object with a `not set` status, rather than returning a `null` object.

### CODE REVIEW

**Comment by chrismerck** [comment]
I don't think we need to `null` the dns and other fields. Just having the `ssid` being `null` should work...

**Comment by marciogranzotto** [comment]
@chrismerck but what will these fields return when there's no Wi-Fi set up?

**Comment by chrismerck** [comment]
Other fields would be `null` if not (yet) set. 

Though I suppose there's a corner case where one may have PATCHed `ssid` to `null` (can you do that?) or set `dns` etc. prior to setting `ssid` where you could have the condition `dns != null & ssid == null` but I don't see the harm in that.

**Comment by chrismerck** [comment]
Sorry, I guess my confusion was about your use of the word "can".

We might consider whether 0.0.0.0 or null is appropriate for the fields that take IPv4 addresses.

**Review by endy-s — APPROVED** [review]

**Pull request merged**
